$(function()
{
    $('.scrollable')
        .jScrollPane()
        .bind(
            'mousewheel',
            function(e)
            {
                e.preventDefault();
            }
        );
});